"""
One-shot script to append 10 enriched records to data/spectator_enriched.csv.
Run from: /Users/chiragrastogi/Dev/research/geopolitics
"""
import csv
import json
import os

ENRICHED_PATH = "data/spectator_enriched.csv"

HEADERS = [
    "id","tweet_id","pub_date","original_text","category","subcategory","countries",
    "entities_people","entities_orgs","entities_weapons","entities_locations",
    "lat","lng","sentiment","severity","is_breaking","summary","context","implications",
    "confirmation_status","source_count","sources_json","images","enriched_at"
]

records = [
    # ── Sports noise tweets ──────────────────────────────────────────────
    {
        "id": "10790",
        "tweet_id": "2069168243500347600",
        "pub_date": "2026-06-22T21:20:03.000Z",
        "original_text": "World Cup leading scorers.\n\n🇦🇷 Lionel Messi: 5\n🇩🇪 Deniz Undav: 3\n🇨🇦 Jonathan David: 3\n🇯🇵 Ayase Ueda: 3",
        "category": "social",
        "subcategory": "sports",
        "countries": "AR;DE;CA;JP;FR;NO;US",
        "entities_people": "Lionel Messi;Deniz Undav;Jonathan David;Ayase Ueda",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "2026 FIFA World Cup top scorers update — Messi leads with 5 goals.",
        "context": "The 2026 FIFA World Cup is underway, hosted jointly by the US, Canada, and Mexico. This tweet is a routine scoring update during the group stage and carries no geopolitical significance.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    {
        "id": "10791",
        "tweet_id": "2069169968911090000",
        "pub_date": "2026-06-22T21:30:03.000Z",
        "original_text": "World Cup leading scorers.\n\n🇦🇷 Lionel Messi: 5\n🇩🇪 Deniz Undav: 3\n🇨🇦 Jonathan David: 3\n🇯🇵 Ayase Ueda: 3",
        "category": "social",
        "subcategory": "sports",
        "countries": "AR;DE;CA;JP",
        "entities_people": "Lionel Messi;Deniz Undav;Jonathan David;Ayase Ueda",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "2026 FIFA World Cup top scorers update — Messi leads with 5 goals.",
        "context": "Routine repeat scoring update during the 2026 FIFA World Cup group stage. No geopolitical relevance.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    {
        "id": "10792",
        "tweet_id": "2069221024852549600",
        "pub_date": "2026-06-23T00:50:03.000Z",
        "original_text": "BREAKING: 🇫🇷 France beat 🇮🇶 Iraq 3-0, as Mbappe scores a double.",
        "category": "social",
        "subcategory": "sports",
        "countries": "FR;IQ",
        "entities_people": "Kylian Mbappe",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "France defeat Iraq 3-0 at 2026 World Cup; Mbappe scores twice.",
        "context": "Group stage match at the 2026 FIFA World Cup. France vs Iraq result with Kylian Mbappe scoring a brace. No geopolitical relevance beyond the sport.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    {
        "id": "10793",
        "tweet_id": "2069221679147143400",
        "pub_date": "2026-06-23T01:00:03.000Z",
        "original_text": "World Cup top scorers, so far.\n\n🇦🇷 Lionel Messi: 5\n🇫🇷 Kylian Mbappe: 4\n🇩🇪 Deniz Undav: 3\n🇨🇦 Jonathan David: 3",
        "category": "social",
        "subcategory": "sports",
        "countries": "AR;FR;DE;CA",
        "entities_people": "Lionel Messi;Kylian Mbappe;Deniz Undav;Jonathan David",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "2026 World Cup top scorers: Messi 5, Mbappe 4, Undav 3, David 3.",
        "context": "Updated top scorers table following France vs Iraq. Routine sports content with no geopolitical relevance.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    # ── Geopolitical: Iran Hormuz ─────────────────────────────────────────
    {
        "id": "10794",
        "tweet_id": "2069226952192573400",
        "pub_date": "2026-06-23T01:20:02.000Z",
        "original_text": "BREAKING: Iran's chief negotiator Mohammad Ghalibaf says Iran will administer the Strait of Hormuz",
        "category": "military",
        "subcategory": "maritime_control",
        "countries": "IR;US;SA;AE",
        "entities_people": "Mohammad Ghalibaf",
        "entities_orgs": "Iranian Parliament;Iran Negotiating Team",
        "entities_weapons": "",
        "entities_locations": "Strait of Hormuz;Switzerland",
        "lat": "26.57",
        "lng": "56.46",
        "sentiment": "escalatory",
        "severity": "4",
        "is_breaking": "TRUE",
        "summary": "Iran's lead negotiator Ghalibaf declares Tehran will administer the Strait of Hormuz post-war.",
        "context": "Iranian Parliament Speaker Mohammad Ghalibaf, returning from Iran-US peace talks in Switzerland, declared that the Strait of Hormuz \"will never go back to the way it was before the war\" and that Iran will administer the waterway while observing international regulations. The announcement follows the Islamabad Memorandum — a ceasefire framework that included reopening of Hormuz to commercial shipping.",
        "implications": "Iran's assertion of administrative control over Hormuz signals intent to leverage its strategic chokehold even within a ceasefire framework; Gulf states and global shipping nations will push back, risking new friction points in post-war negotiations.",
        "confirmation_status": "confirmed",
        "source_count": "4",
        "sources_json": json.dumps([
            {"name": "JNS", "title": "Tehran's chief negotiator: Strait of Hormuz won't return to pre-war status", "url": "https://www.jns.org/news/world/tehrans-chief-negotiator-strait-of-hormuz-wont-return-to-pre-war-status", "quote": "Ghalibaf vowed that conditions in the Strait of Hormuz will never go back to the way they were before the war", "date": "2026-06-23"},
            {"name": "Tribune India", "title": "Hormuz will never go back to its pre-war status: Iran's Parliament Speaker says Iran will manage the strait", "url": "https://www.tribuneindia.com/news/diplomatic-impact/hormuz-will-never-go-back-to-its-pre-war-status-irans-parliament-speaker-says-iran-will-manage-the-strait", "quote": "Iran will manage the Strait of Hormuz going forward", "date": "2026-06-23"},
            {"name": "Express Tribune", "title": "Iran chief negotiator Ghalibaf says Tehran will administer Hormuz", "url": "https://tribune.com.pk/story/2614701/irans-chief-negotiator-ghalibaf-says-tehran-will-administer-hormuz", "quote": "Iran's chief negotiator Ghalibaf says Tehran will administer Hormuz", "date": "2026-06-23"},
            {"name": "The Journal", "title": "Iran says they will administer Strait of Hormuz as peace talks in Switzerland conclude", "url": "https://www.thejournal.ie/iran-strait-of-hormuz-peace-talks-7079041-Jun2026/", "quote": "Iran says they will administer Strait of Hormuz as peace talks in Switzerland conclude", "date": "2026-06-23"},
        ]),
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    # ── Sports: Norway vs Senegal ─────────────────────────────────────────
    {
        "id": "10796",
        "tweet_id": "2069239024896905700",
        "pub_date": "2026-06-23T02:10:03.000Z",
        "original_text": "BREAKING: Haaland double helps 🇳🇴 Norway beat 🇸🇳Senegal 3-2",
        "category": "social",
        "subcategory": "sports",
        "countries": "NO;SN",
        "entities_people": "Erling Haaland",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "Norway beat Senegal 3-2 at 2026 World Cup; Haaland scores twice.",
        "context": "Group stage result at the 2026 FIFA World Cup. Norway defeats Senegal 3-2 with Erling Haaland scoring a brace. Pure sports content with no geopolitical relevance.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    {
        "id": "10795",
        "tweet_id": "2069239995807003000",
        "pub_date": "2026-06-23T02:10:03.000Z",
        "original_text": "Qualified for the knockout phase of the World Cup\n\n🇺🇸 USA\n🇲🇽 Mexico\n🇩🇪 Germany\n🇦🇷 Argentina\n🇫🇷 France\n🇳🇴 Norway",
        "category": "social",
        "subcategory": "sports",
        "countries": "US;MX;DE;AR;FR;NO",
        "entities_people": "",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "USA, Mexico, Germany, Argentina, France, Norway qualify for 2026 World Cup knockouts.",
        "context": "Summary of teams advancing from the group stage of the 2026 FIFA World Cup. Purely sports content.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    # ── Geopolitical: KOSPI crash ─────────────────────────────────────────
    {
        "id": "10797",
        "tweet_id": "2069316242868199700",
        "pub_date": "2026-06-23T07:10:02.000Z",
        "original_text": "BREAKING: 🇰🇷 South Korea's KOSPI index plunges by 10%",
        "category": "economic",
        "subcategory": "market_crash",
        "countries": "KR",
        "entities_people": "",
        "entities_orgs": "Korea Exchange;Samsung Electronics;SK Hynix;Financial Services Commission",
        "entities_weapons": "",
        "entities_locations": "Seoul;South Korea",
        "lat": "37.57",
        "lng": "126.98",
        "sentiment": "escalatory",
        "severity": "4",
        "is_breaking": "TRUE",
        "summary": "KOSPI plunges 9.99% ('Black Tuesday') as chip selloff triggers market-wide trading halt.",
        "context": "South Korea's KOSPI benchmark fell 9.99% on June 23 — its worst single-day drop since March — closing at 8,203.84 after losing 910.71 points. Samsung Electronics and SK Hynix each fell over 12%, triggering a 20-minute automatic circuit breaker. The selloff followed warnings from financial regulators about overleveraged retail investors in chipmaker ETFs, after the KOSPI had surged 94.67% YTD to a historic 9,100+ peak on Monday.",
        "implications": "Circuit breaker activation signals systemic stress; potential contagion to global chip valuations and semiconductor supply chains; South Korean FSC expected to tighten leveraged-product rules in response.",
        "confirmation_status": "confirmed",
        "source_count": "5",
        "sources_json": json.dumps([
            {"name": "Seoul Economic Daily", "title": "'Black Tuesday': KOSPI Plunges Nearly 10%", "url": "https://en.sedaily.com/markets/2026/06/23/black-tuesday-kospi-plunges-nearly-10-percent", "quote": "The benchmark KOSPI closed down 910.71 points at 8,203.84", "date": "2026-06-23"},
            {"name": "MarketScreener / Reuters", "title": "South Korea's KOSPI plunges nearly 10% after regulator cautions on leveraged ETFs", "url": "https://www.marketscreener.com/news/south-korea-s-kospi-plunges-nearly-10-after-regulator-cautions-on-leveraged-etfs-ce7f5fdadb81f02d", "quote": "KOSPI plunges nearly 10% after regulator cautions on leveraged ETFs", "date": "2026-06-23"},
            {"name": "TradingView / Reuters", "title": "South Korea's KOSPI plunges nearly 10% after regulator cautions on leveraged ETFs", "url": "https://www.tradingview.com/news/reuters.com,2026:newsml_L1N42V06D:0-south-korea-s-kospi-plunges-nearly-10-after-regulator-cautions-on-leveraged-etfs/", "quote": "Samsung Electronics and SK Hynix shed more than 12% each, triggering a 20-minute trading halt", "date": "2026-06-23"},
            {"name": "India Infoline", "title": "South Korea Stock Market Crash: KOSPI Plunges Nearly 10% in Sharp Tech Selloff", "url": "https://www.indiainfoline.com/news/international/south-korea-stock-market-crash-kospi-plunges-nearly-10-in-sharp-tech-selloff", "quote": "KOSPI plunges nearly 10% in sharp tech selloff as chip giants Samsung and SK Hynix lead losses", "date": "2026-06-23"},
            {"name": "HDFC Sky", "title": "South Korea's KOSPI Plunges 10% as Samsung, SK Hynix Lead Selloff", "url": "https://hdfcsky.com/news/kospi-crashes-10percent-as-samsung-sk-hynix-lead-selloff", "quote": "The KOSPI has risen 94.67% so far this year, making it one of the world's best-performing markets", "date": "2026-06-23"},
        ]),
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    # ── Sports: Scorers update ────────────────────────────────────────────
    {
        "id": "10798",
        "tweet_id": "2069359345851355400",
        "pub_date": "2026-06-23T10:00:02.000Z",
        "original_text": "World Cup top scorers, so far.\n\n🇦🇷 Lionel Messi: 5\n🇫🇷 Kylian Mbappe: 4\n🇳🇴 Erling Haaland: 4\n🇩🇪 Deniz Undav: 3",
        "category": "social",
        "subcategory": "sports",
        "countries": "AR;FR;NO;DE",
        "entities_people": "Lionel Messi;Kylian Mbappe;Erling Haaland;Deniz Undav",
        "entities_orgs": "FIFA World Cup 2026",
        "entities_weapons": "",
        "entities_locations": "World Cup 2026",
        "lat": "",
        "lng": "",
        "sentiment": "neutral",
        "severity": "1",
        "is_breaking": "FALSE",
        "summary": "2026 World Cup top scorers: Messi 5, Mbappe 4, Haaland 4, Undav 3.",
        "context": "Updated scorers table after Norway vs Senegal. Routine sports content with no geopolitical relevance.",
        "implications": "No geopolitical implications.",
        "confirmation_status": "confirmed",
        "source_count": "0",
        "sources_json": "[]",
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
    # ── Geopolitical: Iran president in Pakistan ──────────────────────────
    {
        "id": "10799",
        "tweet_id": "2069370184717267200",
        "pub_date": "2026-06-23T10:50:01.000Z",
        "original_text": "BREAKING: Iran's president has arrived in Pakistan",
        "category": "diplomatic",
        "subcategory": "state_visit",
        "countries": "IR;PK;US",
        "entities_people": "Masoud Pezeshkian;Asif Ali Zardari;Shehbaz Sharif",
        "entities_orgs": "Government of Iran;Government of Pakistan",
        "entities_weapons": "",
        "entities_locations": "Islamabad;Pakistan",
        "lat": "33.72",
        "lng": "73.06",
        "sentiment": "de-escalatory",
        "severity": "3",
        "is_breaking": "TRUE",
        "summary": "Iranian President Pezeshkian arrives in Islamabad to thank Pakistan for brokering Islamabad Memorandum.",
        "context": "President Masoud Pezeshkian arrived in Islamabad on June 23 for his first overseas trip since the Iran-US war, a day after Switzerland peace talks. The visit is to express appreciation for Pakistan's mediation role in the Islamabad Memorandum — a ceasefire framework covering Hormuz reopening, Lebanon, and pathways to nuclear/sanctions negotiations. He will meet President Zardari and PM Sharif.",
        "implications": "Pakistan's consolidation as key Iran-US mediator raises Islamabad's regional influence; Iran-Pakistan bilateral ties expected to deepen across trade, energy, and connectivity as diplomatic dividend.",
        "confirmation_status": "confirmed",
        "source_count": "5",
        "sources_json": json.dumps([
            {"name": "Al Jazeera", "title": "Why Iran's President Pezeshkian is heading to Pakistan after US talks", "url": "https://www.aljazeera.com/news/2026/6/23/why-irans-president-pezeshkian-is-heading-to-pakistan-after-us-iran-talks", "quote": "Pezeshkian's visit to Pakistan is aimed at expressing appreciation for Islamabad's role in facilitating the Iran-US Islamabad Memorandum", "date": "2026-06-23"},
            {"name": "Bloomberg", "title": "Iran President Pezeshkian to Visit Pakistan After US-Iran Truce", "url": "https://www.bloomberg.com/news/articles/2026-06-23/iran-president-to-visit-pakistan-following-historic-deal-with-us", "quote": "Iran President Pezeshkian to Visit Pakistan After US-Iran Truce", "date": "2026-06-23"},
            {"name": "Arab News", "title": "Iranian president lands in Pakistan, visit to advance Islamabad Memorandum implementation", "url": "https://www.arabnews.com/node/2648241/pakistan", "quote": "Visit to advance Islamabad Memorandum implementation", "date": "2026-06-23"},
            {"name": "The Inquirer", "title": "Iranian president lands in Pakistan as US-Iran teams work to finalize a war-ending deal", "url": "https://www.inquirer.com/news/nation-world/iran-president-war-negotiations-pakistan-20260623.html", "quote": "Iranian president lands in Pakistan as US-Iran teams work to finalize a war-ending deal", "date": "2026-06-23"},
            {"name": "Dawn", "title": "Iran President Masoud Pezeshkian to visit Pakistan", "url": "https://www.dawn.com/news/2010038", "quote": "Iran President Masoud Pezeshkian to visit Pakistan", "date": "2026-06-23"},
        ]),
        "images": "",
        "enriched_at": "2026-06-23T11:30:00.000Z",
    },
]

# Write to CSV — append if exists, create with headers if not
file_exists = os.path.isfile(ENRICHED_PATH)

with open(ENRICHED_PATH, "a", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_ALL)
    if not file_exists:
        writer.writeheader()
    for rec in records:
        writer.writerow(rec)

print(f"Appended {len(records)} records to {ENRICHED_PATH}")
print(f"IDs written: {[r['id'] for r in records]}")
