#!/usr/bin/env python3
"""
Build SQLite database from all CSV files and export data/database.json.

Usage (from project root):
  python scripts/build_db.py

Imports: incidents.csv, operations.csv, imagery.csv, tweet_enriched.csv,
         enriched_actions.csv (if present — generated by enrich_actions_agent.js)

Exports: data/database.json (single file for the frontend DataLayer)
         data/geopolitics.db (SQLite for backend queries / agent reads)
"""

import csv
import json
import os
import sqlite3
from datetime import datetime

ROOT     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, 'data')
DB_PATH  = os.path.join(DATA_DIR, 'geopolitics.db')
OUT_PATH = os.path.join(DATA_DIR, 'database.json')


# ── Helpers ───────────────────────────────────────────────────────────────────

def read_csv(path):
    if not os.path.exists(path):
        return []
    with open(path, encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = []
        for row in reader:
            # Skip accidental duplicate-header rows
            if row.get(reader.fieldnames[0]) == reader.fieldnames[0]:
                continue
            rows.append(dict(row))
    return rows


def date_to_sort_value(ts_str):
    """
    Map an ISO timestamp to the TL_MARKS date_sort_value scale used by the
    frontend timeline.  Interpolates linearly between known mark points.
    """
    marks = [
        (datetime(2023, 10,  1),  -60),
        (datetime(2024,  4,  1),  -35),
        (datetime(2024,  8,  1),  -25),
        (datetime(2024, 11,  1),  -15),
        (datetime(2025,  6,  1),    0),
        (datetime(2025,  9,  1),   18),
        (datetime(2025, 12,  1),   32),
        (datetime(2026,  1,  1),   45),
        (datetime(2026,  2, 28),   65),
        (datetime(2026,  3,  1),   82),
        (datetime(2026,  3, 24),  100),
    ]
    try:
        # Accept "2026-03-24 16:40:02" or ISO 8601 with T/Z
        ts_str = ts_str.replace('T', ' ').replace('Z', '').split('+')[0].strip()
        dt = datetime.strptime(ts_str[:19], '%Y-%m-%d %H:%M:%S')
    except Exception:
        return 0

    for i in range(len(marks) - 1):
        lo_dt, lo_v = marks[i]
        hi_dt, hi_v = marks[i + 1]
        if lo_dt <= dt <= hi_dt:
            span = (hi_dt - lo_dt).total_seconds()
            frac = (dt - lo_dt).total_seconds() / span
            return round(lo_v + frac * (hi_v - lo_v), 2)
    return -60 if dt < marks[0][0] else 100


# ── Database setup ─────────────────────────────────────────────────────────────

INCIDENTS_SCHEMA = '''
CREATE TABLE IF NOT EXISTS incidents (
    incident_id             TEXT PRIMARY KEY,
    operation_name          TEXT,
    operation_color         TEXT,
    incident_title          TEXT,
    date                    TEXT,
    date_sort_value         REAL,
    strike_type             TEXT,
    confirmed               TEXT,
    origin_lat              TEXT,
    origin_lng              TEXT,
    origin_label            TEXT,
    origin_sublabel         TEXT,
    target_lat              TEXT,
    target_lng              TEXT,
    target_label            TEXT,
    target_sublabel         TEXT,
    summary                 TEXT,
    assessment              TEXT,
    platform_or_unit        TEXT,
    munitions_weapons       TEXT,
    munitions_quantity      TEXT,
    range_km                TEXT,
    target_type             TEXT,
    target_depth_hardening  TEXT,
    military_kia_friendly   TEXT,
    military_kia_enemy      TEXT,
    civilian_kia            TEXT,
    military_wia_friendly   TEXT,
    personnel_deployed      TEXT,
    aircraft_deployed       TEXT,
    naval_vessels           TEXT,
    result_outcome          TEXT,
    nuclear_setback_assessment TEXT,
    economic_impact         TEXT,
    intercepted_munitions   TEXT,
    key_intelligence_notes  TEXT,
    osint_sources           TEXT,
    press_sources           TEXT,
    think_tank_sources      TEXT,
    tags                    TEXT,
    badge_colors            TEXT,
    is_retaliation          TEXT,
    is_covert               TEXT,
    is_first_use            TEXT,
    disputed                TEXT,
    source_type             TEXT DEFAULT 'curated'
)'''

INCIDENT_COLS = [
    'incident_id','operation_name','operation_color','incident_title','date',
    'date_sort_value','strike_type','confirmed',
    'origin_lat','origin_lng','origin_label','origin_sublabel',
    'target_lat','target_lng','target_label','target_sublabel',
    'summary','assessment','platform_or_unit','munitions_weapons',
    'munitions_quantity','range_km','target_type','target_depth_hardening',
    'military_kia_friendly','military_kia_enemy','civilian_kia',
    'military_wia_friendly','personnel_deployed','aircraft_deployed',
    'naval_vessels','result_outcome','nuclear_setback_assessment',
    'economic_impact','intercepted_munitions','key_intelligence_notes',
    'osint_sources','press_sources','think_tank_sources',
    'tags','badge_colors','is_retaliation','is_covert','is_first_use',
    'disputed','source_type',
]


def build():
    conn = sqlite3.connect(DB_PATH)
    c    = conn.cursor()

    # ── Create tables ──────────────────────────────────────────────────────────
    c.execute(INCIDENTS_SCHEMA)

    c.execute('''
    CREATE TABLE IF NOT EXISTS operations (
        operation_name TEXT PRIMARY KEY,
        color          TEXT,
        countries      TEXT,
        period         TEXT,
        dashed         TEXT
    )''')

    c.execute('''
    CREATE TABLE IF NOT EXISTS imagery (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        incident_id TEXT,
        label       TEXT,
        url         TEXT,
        caption     TEXT,
        source      TEXT
    )''')

    c.execute('''
    CREATE TABLE IF NOT EXISTS tweets (
        created_at          TEXT PRIMARY KEY,
        category            TEXT,
        subcategory         TEXT,
        countries           TEXT,
        entities_people     TEXT,
        entities_orgs       TEXT,
        entities_weapons    TEXT,
        entities_locations  TEXT,
        lat                 TEXT,
        lng                 TEXT,
        location_confidence TEXT,
        sentiment           TEXT,
        severity            TEXT,
        linked_incident_ids TEXT,
        linked_operation    TEXT,
        is_breaking         TEXT,
        summary             TEXT
    )''')

    conn.commit()

    # ── Import operations ──────────────────────────────────────────────────────
    ops = read_csv(os.path.join(DATA_DIR, 'operations.csv'))
    for r in ops:
        c.execute(
            'INSERT OR REPLACE INTO operations VALUES (?,?,?,?,?)',
            [r.get('operation_name',''), r.get('color',''),
             r.get('countries',''),      r.get('period',''),
             r.get('dashed','')]
        )
    print(f'  Operations: {len(ops)} rows')

    # Build ops lookup: name → color
    ops_color = {r.get('operation_name',''): r.get('color','') for r in ops}

    # ── Import imagery ─────────────────────────────────────────────────────────
    c.execute('DELETE FROM imagery')
    imgs = read_csv(os.path.join(DATA_DIR, 'imagery.csv'))
    for r in imgs:
        c.execute(
            'INSERT INTO imagery (incident_id,label,url,caption,source) VALUES (?,?,?,?,?)',
            [r.get('incident_id',''), r.get('label',''),
             r.get('url',''),         r.get('caption',''),
             r.get('source','')]
        )
    print(f'  Imagery: {len(imgs)} rows')

    # ── Import curated incidents ───────────────────────────────────────────────
    incidents = read_csv(os.path.join(DATA_DIR, 'incidents.csv'))
    curated_ids = set()
    for r in incidents:
        r['source_type'] = 'curated'
        vals = [r.get(col, '') for col in INCIDENT_COLS]
        c.execute(
            f'INSERT OR REPLACE INTO incidents VALUES ({",".join(["?"]*len(INCIDENT_COLS))})',
            vals
        )
        curated_ids.add(r.get('incident_id', ''))
    print(f'  Curated incidents: {len(incidents)} rows')

    # ── Import enriched actions (from enrich_actions_agent) ───────────────────
    ea_path = os.path.join(DATA_DIR, 'enriched_actions.csv')
    enriched = read_csv(ea_path)
    skipped = 0
    for r in enriched:
        iid = r.get('incident_id', '')
        if iid in curated_ids:
            skipped += 1
            continue
        r.setdefault('source_type', 'enriched')
        # Fill operation_color if blank
        if not r.get('operation_color') and r.get('operation_name'):
            r['operation_color'] = ops_color.get(r['operation_name'], '#9e9e9e')
        vals = [r.get(col, '') for col in INCIDENT_COLS]
        c.execute(
            f'INSERT OR REPLACE INTO incidents VALUES ({",".join(["?"]*len(INCIDENT_COLS))})',
            vals
        )
    print(f'  Enriched actions: {len(enriched)} rows ({skipped} skipped as dupes)')

    # ── Import enriched tweets ─────────────────────────────────────────────────
    tweet_path = os.path.join(DATA_DIR, 'tweet_enriched.csv')
    tweets = read_csv(tweet_path)
    inserted_tweets = 0
    for r in tweets:
        try:
            c.execute(
                'INSERT OR IGNORE INTO tweets VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
                [r.get('created_at',''),          r.get('category',''),
                 r.get('subcategory',''),          r.get('countries',''),
                 r.get('entities_people',''),      r.get('entities_orgs',''),
                 r.get('entities_weapons',''),     r.get('entities_locations',''),
                 r.get('lat',''),                  r.get('lng',''),
                 r.get('location_confidence',''),  r.get('sentiment',''),
                 r.get('severity',''),             r.get('linked_incident_ids',''),
                 r.get('linked_operation',''),     r.get('is_breaking',''),
                 r.get('summary','')]
            )
            inserted_tweets += 1
        except Exception:
            pass
    print(f'  Tweets: {inserted_tweets} rows')

    conn.commit()

    # ── Export JSON ────────────────────────────────────────────────────────────
    export_json(conn, OUT_PATH)
    conn.close()
    print(f'\nDatabase: {DB_PATH}')
    print(f'Export:   {OUT_PATH}')


def export_json(conn, out_path):
    def query(sql, params=()):
        cur = conn.cursor()
        cur.execute(sql, params)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]

    incidents  = query('SELECT * FROM incidents  ORDER BY CAST(date_sort_value AS REAL)')
    operations = query('SELECT * FROM operations')
    imagery    = query('SELECT * FROM imagery')
    # Return 2000 most-recent tweets for the intel feed
    tweets     = query('SELECT * FROM tweets ORDER BY created_at DESC LIMIT 2000')

    curated  = [i for i in incidents if i.get('source_type') == 'curated']
    enriched = [i for i in incidents if i.get('source_type') == 'enriched']

    data = {
        '_meta': {
            'generated': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
            'version':   2,
            'counts': {
                'incidents_curated':  len(curated),
                'incidents_enriched': len(enriched),
                'incidents_total':    len(incidents),
                'operations':         len(operations),
                'imagery':            len(imagery),
                'tweets':             len(tweets),
            }
        },
        'incidents':  incidents,
        'operations': operations,
        'imagery':    imagery,
        'tweets':     tweets,
    }

    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))

    print(f'\nExported:')
    print(f'  {len(curated)} curated incidents + {len(enriched)} enriched actions = {len(incidents)} total')
    print(f'  {len(operations)} operations, {len(imagery)} imagery, {len(tweets)} tweets')
    size_kb = os.path.getsize(out_path) // 1024
    print(f'  database.json: {size_kb} KB')


if __name__ == '__main__':
    print('Building database...')
    build()
    print('\nDone.')
